# Cloudflare Pages 配置
[build]
  command = "cd client && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"

# 环境变量 - 替换为你的实际值
[build.environment_variables]
  REACT_APP_API_URL = "https://mymemo-api.your-subdomain.workers.dev"
  REACT_APP_AUTH0_DOMAIN = "dev-supk23n0xgucx0no.us.auth0.com"
  REACT_APP_AUTH0_CLIENT_ID = "your-auth0-client-id"
  REACT_APP_AUTH0_AUDIENCE = "https://dev-supk23n0xgucx0no.us.auth0.com/api/v2/"

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "https://mymemo-api.your-subdomain.workers.dev/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200