[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm ci"

[deploy]
startCommand = "cd server && npm run build && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
